include:
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/core.yml"
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/typescript.yml"
  - project: "quickstart-templates/ci-templates"
    ref: master
    file: "node/meta.yml"
